/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design System Stitch Tokens
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#93000a",
        "text-main": "#0F172A",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "text-muted": "#64748B",
        "secondary-fixed-dim": "#b0c6ff",
        "outline": "#737686",
        "on-secondary-fixed-variant": "#1a438e",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#261900",
        "on-tertiary-fixed-variant": "#5d4200",
        "inverse-on-surface": "#eff1f3",
        "on-primary-container": "#eeefff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c3c6d7",
        "bg-pure": "#FFFFFF",
        "on-background": "#191c1e",
        "secondary": "#375ca8",
        "on-secondary-fixed": "#001945",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-container": "#8aacfe",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#003ea8",
        "primary-container": "#2563eb",
        "secondary-fixed": "#d9e2ff",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "primary": "#004ac6",
        "surface-tint": "#0053db",
        "primary-fixed-dim": "#b4c5ff",
        "map-accent": "#006CE4",
        "tertiary-fixed-dim": "#febb02",
        "on-surface-variant": "#434655",
        "on-secondary": "#ffffff",
        "border-subtle": "#E2E8F0",
        "tertiary-container": "#8e6700",
        "inverse-primary": "#b4c5ff",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffefd6",
        "on-secondary-container": "#113e89",
        "tertiary": "#6f5000",
        "tertiary-fixed": "#ffdea4",
        "on-primary-fixed": "#00174b",

        // Backgrounds
        surfaceLegacy: {
          DEFAULT: '#FFFFFF',
          secondary: '#F8FAFC',
          tertiary: '#F1F5F9',
        },
        // Accent Blue (Primary Brand)
        brand: {
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
        // Slate Text
        slate: {
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
        success: '#10B981',
        warning: '#F59E0B',
        danger: '#EF4444',
      },
      fontFamily: {
        sans: ['Inter', 'SF Pro Display', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        // Design System
        "headline-md": ["Inter"],
        "caption": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '1rem' }],
        // Design system
        "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
      },
      borderRadius: {
        'xl': '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
        'full': '9999px',
        // Design system
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'std': '16px',
        'container': '24px',
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(15, 23, 42, 0.05)',
        'card-hover': '0px 10px 30px rgba(15, 23, 42, 0.12)',
        'panel': '0 0 0 1px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.06)',
        'float': '0 8px 32px rgba(37,99,235,0.25)',
        'floating': '0px 10px 30px rgba(15, 23, 42, 0.12)',
        'input': '0 0 0 3px rgba(37,99,235,0.1)',
        'sm-soft': '0 1px 4px rgba(0,0,0,0.06)',
      },
      spacing: {
        // Design system
        "margin-mobile": "16px",
        "container-max": "1280px",
        "xs": "4px",
        "sm": "12px",
        "xl": "80px",
        "lg": "48px",
        "md": "24px",
        "base": "8px",
        "gutter": "24px"
      },
      letterSpacing: {
        'tighter': '-0.04em',
        'tight': '-0.025em',
        'normal': '-0.01em',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16,1,0.3,1)',
        'scale-in': 'scaleIn 0.2s ease-out',
        'shimmer': 'shimmer 1.8s infinite',
        'float': 'float 3s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
        'bounce-soft': 'bounceSoft 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        bounceSoft: {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
    },
  },
  plugins: [],
}
